version: '3.4'

services:
  dev:
    image: node:12-alpine
    container_name: new_store_api_dev
    command:  npm run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
    networks:
      - store-network
    depends_on:
      - db
services:
  test:
    image: node:12-alpine
    container_name: new_store_api_test
    command:  npm run test
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - ./:/app:cached
    networks:
      - store-network
    depends_on:
      - db

  db:
    image: postgres
    container_name: new_store_db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - store-network

volumes:
  database:

networks:
  store-network:
    driver: bridge
